/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import Logica.CargoEmpleado;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author breiner
 */
public class VCargoEmpleado extends javax.swing.JFrame {

    CargoEmpleado ce = new CargoEmpleado(); 
    
    /** Creates new form VCargoEmpleado */
    public VCargoEmpleado() throws SQLException {
        initComponents();
        pnl_Encabezado.setBackground(new Color(0,0,0,195));
        setLocationRelativeTo(null);
        setResizable(false);
        
        ce.ShowDataBoxSearchCargoEMP();
        ce.ShowDataCargoEMP();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Encabezado = new javax.swing.JPanel();
        jbtn_MIn = new javax.swing.JLabel();
        txt_Cerrar = new javax.swing.JLabel();
        jtxt_Titulo = new javax.swing.JLabel();
        jbtn_home = new javax.swing.JLabel();
        Encabezado = new javax.swing.JLabel();
        pnl_RegistroCargoEmpleado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_NombreCE = new javax.swing.JTextField();
        btn_RegistrarCE = new javax.swing.JButton();
        pnl_MostrarCargoEmpleado = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaCargoEMP = new javax.swing.JTable();
        btn_ActualizarCE = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Box_BuscarCE = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        txt_BuscarCE = new javax.swing.JTextField();
        jbtn_BuscarCE = new javax.swing.JLabel();
        btn_EliminarCE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Encabezado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn_MIn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbtn_MIn.setForeground(new java.awt.Color(57, 113, 177));
        jbtn_MIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtn_MIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minizar2.png"))); // NOI18N
        jbtn_MIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_MInMouseClicked(evt);
            }
        });
        pnl_Encabezado.add(jbtn_MIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 20, 30));

        txt_Cerrar.setForeground(new java.awt.Color(57, 113, 177));
        txt_Cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close2.png"))); // NOI18N
        txt_Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_CerrarMouseClicked(evt);
            }
        });
        pnl_Encabezado.add(txt_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 20, 30));

        jtxt_Titulo.setBackground(new java.awt.Color(204, 204, 204));
        jtxt_Titulo.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        jtxt_Titulo.setForeground(new java.awt.Color(57, 113, 157));
        jtxt_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtxt_Titulo.setText("Cargo de Empleado");
        pnl_Encabezado.add(jtxt_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 770, -1));

        jbtn_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home1.png"))); // NOI18N
        jbtn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_homeMouseClicked(evt);
            }
        });
        pnl_Encabezado.add(jbtn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        getContentPane().add(pnl_Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 60));

        Encabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/encabezado.jpg"))); // NOI18N
        getContentPane().add(Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 60));

        pnl_RegistroCargoEmpleado.setBackground(new java.awt.Color(32, 33, 35));
        pnl_RegistroCargoEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(57, 113, 177));
        jLabel2.setText("Nombre");
        pnl_RegistroCargoEmpleado.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        pnl_RegistroCargoEmpleado.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 210, 10));

        txt_NombreCE.setBackground(new java.awt.Color(32, 33, 35));
        txt_NombreCE.setForeground(new java.awt.Color(255, 255, 255));
        txt_NombreCE.setBorder(null);
        pnl_RegistroCargoEmpleado.add(txt_NombreCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 210, 30));

        btn_RegistrarCE.setBackground(new java.awt.Color(126, 87, 194));
        btn_RegistrarCE.setFont(new java.awt.Font("NanumMyeongjo", 1, 12)); // NOI18N
        btn_RegistrarCE.setForeground(new java.awt.Color(255, 255, 255));
        btn_RegistrarCE.setText("Registrar");
        btn_RegistrarCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarCEActionPerformed(evt);
            }
        });
        pnl_RegistroCargoEmpleado.add(btn_RegistrarCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 290, 40));

        getContentPane().add(pnl_RegistroCargoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 390, 500));

        pnl_MostrarCargoEmpleado.setBackground(new java.awt.Color(0, 0, 0));
        pnl_MostrarCargoEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(32, 33, 35));

        TablaCargoEMP.setForeground(new java.awt.Color(0, 0, 0));
        TablaCargoEMP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        TablaCargoEMP.setSelectionBackground(new java.awt.Color(32, 33, 35));
        TablaCargoEMP.setSelectionForeground(new java.awt.Color(57, 113, 177));
        jScrollPane2.setViewportView(TablaCargoEMP);

        pnl_MostrarCargoEmpleado.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 310));

        btn_ActualizarCE.setBackground(new java.awt.Color(126, 87, 194));
        btn_ActualizarCE.setFont(new java.awt.Font("NanumMyeongjo", 1, 12)); // NOI18N
        btn_ActualizarCE.setForeground(new java.awt.Color(255, 255, 255));
        btn_ActualizarCE.setText("Mostrar Todo");
        btn_ActualizarCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarCEActionPerformed(evt);
            }
        });
        pnl_MostrarCargoEmpleado.add(btn_ActualizarCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 130, 40));

        jLabel8.setForeground(new java.awt.Color(57, 113, 177));
        jLabel8.setText("Buscar");
        pnl_MostrarCargoEmpleado.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, -1, 20));

        Box_BuscarCE.setBackground(new java.awt.Color(32, 33, 35));
        Box_BuscarCE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnl_MostrarCargoEmpleado.add(Box_BuscarCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 100, 30));
        pnl_MostrarCargoEmpleado.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 280, 10));

        txt_BuscarCE.setBackground(new java.awt.Color(0, 0, 0));
        txt_BuscarCE.setForeground(new java.awt.Color(204, 204, 204));
        txt_BuscarCE.setBorder(null);
        pnl_MostrarCargoEmpleado.add(txt_BuscarCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 240, 20));

        jbtn_BuscarCE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtn_BuscarCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/searcher2.png"))); // NOI18N
        jbtn_BuscarCE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_BuscarCEMouseClicked(evt);
            }
        });
        pnl_MostrarCargoEmpleado.add(jbtn_BuscarCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 30, 30));

        btn_EliminarCE.setBackground(new java.awt.Color(126, 87, 194));
        btn_EliminarCE.setFont(new java.awt.Font("NanumMyeongjo", 1, 12)); // NOI18N
        btn_EliminarCE.setForeground(new java.awt.Color(255, 255, 255));
        btn_EliminarCE.setText("Eliminar");
        btn_EliminarCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarCEActionPerformed(evt);
            }
        });
        pnl_MostrarCargoEmpleado.add(btn_EliminarCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, 40));

        getContentPane().add(pnl_MostrarCargoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 470, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_MInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_MInMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_jbtn_MInMouseClicked

    private void txt_CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_CerrarMouseClicked
        dispose();
    }//GEN-LAST:event_txt_CerrarMouseClicked

    private void btn_RegistrarCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarCEActionPerformed

        String nombre = txt_NombreCE.getText();

        try {
            ce.InsertCargoEMP(nombre);
        } catch (SQLException ex) {
            Logger.getLogger(VProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_RegistrarCEActionPerformed

    private void btn_ActualizarCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarCEActionPerformed
        try {
            ce.ShowDataCargoEMP();
        } catch (SQLException ex) {
            Logger.getLogger(VProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_ActualizarCEActionPerformed

    private void jbtn_BuscarCEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_BuscarCEMouseClicked
        String buscarPor = (String)Box_BuscarCE.getSelectedItem();
        String dato = txt_BuscarCE.getText();
        String datL = "'"+dato+"'";

        System.out.println(datL);

        if(buscarPor.equals("NOMBRE")){
            try {
                ce.SearchDataCargoEMP(buscarPor, datL);
                ce.ShowDataCargoEMP(buscarPor, datL);
            } catch (SQLException ex) {
                Logger.getLogger(VCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                ce.SearchDataCargoEMP(buscarPor, dato);
                ce.ShowDataCargoEMP(buscarPor, dato);
            } catch (SQLException ex) {
                Logger.getLogger(VCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtn_BuscarCEMouseClicked

    private void btn_EliminarCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarCEActionPerformed
        String id = String.valueOf((String)TablaCargoEMP.getValueAt(TablaCargoEMP.getSelectedRow(),0));

        try {
            ce.DeleteDataCargoEMP(id);
        } catch (SQLException ex) {
            Logger.getLogger(VProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_EliminarCEActionPerformed

    private void jbtn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_homeMouseClicked
        Home home = new Home();

        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtn_homeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCargoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCargoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCargoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCargoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VCargoEmpleado().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VCargoEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> Box_BuscarCE;
    private javax.swing.JLabel Encabezado;
    public static javax.swing.JTable TablaCargoEMP;
    private javax.swing.JButton btn_ActualizarCE;
    private javax.swing.JButton btn_EliminarCE;
    private javax.swing.JButton btn_RegistrarCE;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jbtn_BuscarCE;
    private javax.swing.JLabel jbtn_MIn;
    private javax.swing.JLabel jbtn_home;
    private javax.swing.JLabel jtxt_Titulo;
    private javax.swing.JPanel pnl_Encabezado;
    private javax.swing.JPanel pnl_MostrarCargoEmpleado;
    private javax.swing.JPanel pnl_RegistroCargoEmpleado;
    private javax.swing.JTextField txt_BuscarCE;
    private javax.swing.JLabel txt_Cerrar;
    private javax.swing.JTextField txt_NombreCE;
    // End of variables declaration//GEN-END:variables

}
