/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Logica.CategoriaProducto;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author breiner
 */
public class VCategoriaProducto extends javax.swing.JFrame {

    CategoriaProducto cp = new CategoriaProducto();
    
    /**
     * Creates new form VCategoria
     */
    public VCategoriaProducto() throws SQLException {
        initComponents();
        pnl_Encabezado.setBackground(new Color(0,0,0,195));
        setLocationRelativeTo(null);
        setResizable(false);
        
        cp.ShowDataCategoriaPD();
        cp.ShowDataBoxSearchCategoriaPD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Encabezado = new javax.swing.JPanel();
        jbtn_MIn = new javax.swing.JLabel();
        txt_Cerrar = new javax.swing.JLabel();
        jtxt_Titulo = new javax.swing.JLabel();
        jbtn_home2 = new javax.swing.JLabel();
        Encabezado = new javax.swing.JLabel();
        pnl_RegistroCategoriaProducto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_NombreCP = new javax.swing.JTextField();
        btn_RegistrarCP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txA_DescripcionCP = new javax.swing.JTextArea();
        pnl_MostrarCategoriaProducto = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaCategoriaPD = new javax.swing.JTable();
        btn_ActualizarCP = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Box_BuscarCP = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        txt_BuscarCP = new javax.swing.JTextField();
        jbtn_BuscarCP = new javax.swing.JLabel();
        btn_EliminarCP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Encabezado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn_MIn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbtn_MIn.setForeground(new java.awt.Color(57, 113, 177));
        jbtn_MIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtn_MIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minizar2.png"))); // NOI18N
        jbtn_MIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_MInMouseClicked(evt);
            }
        });
        pnl_Encabezado.add(jbtn_MIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 20, 30));

        txt_Cerrar.setForeground(new java.awt.Color(57, 113, 177));
        txt_Cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close2.png"))); // NOI18N
        txt_Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_CerrarMouseClicked(evt);
            }
        });
        pnl_Encabezado.add(txt_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 20, 30));

        jtxt_Titulo.setBackground(new java.awt.Color(204, 204, 204));
        jtxt_Titulo.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        jtxt_Titulo.setForeground(new java.awt.Color(57, 113, 157));
        jtxt_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtxt_Titulo.setText("Categoria de Producto");
        pnl_Encabezado.add(jtxt_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 770, -1));

        jbtn_home2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtn_home2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home1.png"))); // NOI18N
        jbtn_home2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_home2MouseClicked(evt);
            }
        });
        pnl_Encabezado.add(jbtn_home2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        getContentPane().add(pnl_Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 60));

        Encabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/encabezado.jpg"))); // NOI18N
        getContentPane().add(Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 60));

        pnl_RegistroCategoriaProducto.setBackground(new java.awt.Color(32, 33, 35));
        pnl_RegistroCategoriaProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(52, 52, 54));
        jLabel2.setText("Descripcion");
        pnl_RegistroCategoriaProducto.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        pnl_RegistroCategoriaProducto.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 230, 10));

        txt_NombreCP.setBackground(new java.awt.Color(32, 33, 35));
        txt_NombreCP.setForeground(new java.awt.Color(255, 255, 255));
        txt_NombreCP.setBorder(null);
        txt_NombreCP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_NombreCPFocusGained(evt);
            }
        });
        pnl_RegistroCategoriaProducto.add(txt_NombreCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 230, 30));

        btn_RegistrarCP.setBackground(new java.awt.Color(126, 87, 194));
        btn_RegistrarCP.setFont(new java.awt.Font("NanumMyeongjo", 1, 12)); // NOI18N
        btn_RegistrarCP.setForeground(new java.awt.Color(255, 255, 255));
        btn_RegistrarCP.setText("Registrar");
        btn_RegistrarCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarCPActionPerformed(evt);
            }
        });
        pnl_RegistroCategoriaProducto.add(btn_RegistrarCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 320, 40));

        jLabel3.setForeground(new java.awt.Color(57, 113, 177));
        jLabel3.setText("Nombre");
        pnl_RegistroCategoriaProducto.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        txA_DescripcionCP.setColumns(20);
        txA_DescripcionCP.setRows(5);
        txA_DescripcionCP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txA_DescripcionCPFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(txA_DescripcionCP);

        pnl_RegistroCategoriaProducto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 240, 100));

        getContentPane().add(pnl_RegistroCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 390, 500));

        pnl_MostrarCategoriaProducto.setBackground(new java.awt.Color(0, 0, 0));
        pnl_MostrarCategoriaProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(32, 33, 35));

        TablaCategoriaPD.setForeground(new java.awt.Color(0, 0, 0));
        TablaCategoriaPD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        TablaCategoriaPD.setSelectionBackground(new java.awt.Color(32, 33, 35));
        TablaCategoriaPD.setSelectionForeground(new java.awt.Color(57, 113, 177));
        jScrollPane2.setViewportView(TablaCategoriaPD);

        pnl_MostrarCategoriaProducto.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 310));

        btn_ActualizarCP.setBackground(new java.awt.Color(126, 87, 194));
        btn_ActualizarCP.setFont(new java.awt.Font("NanumMyeongjo", 1, 12)); // NOI18N
        btn_ActualizarCP.setForeground(new java.awt.Color(255, 255, 255));
        btn_ActualizarCP.setText("Mostrar Todo");
        btn_ActualizarCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarCPActionPerformed(evt);
            }
        });
        pnl_MostrarCategoriaProducto.add(btn_ActualizarCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 130, 40));

        jLabel8.setForeground(new java.awt.Color(57, 113, 177));
        jLabel8.setText("Buscar");
        pnl_MostrarCategoriaProducto.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, -1, 20));

        Box_BuscarCP.setBackground(new java.awt.Color(32, 33, 35));
        Box_BuscarCP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnl_MostrarCategoriaProducto.add(Box_BuscarCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 100, 30));
        pnl_MostrarCategoriaProducto.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 280, 10));

        txt_BuscarCP.setBackground(new java.awt.Color(0, 0, 0));
        txt_BuscarCP.setForeground(new java.awt.Color(204, 204, 204));
        txt_BuscarCP.setBorder(null);
        pnl_MostrarCategoriaProducto.add(txt_BuscarCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 240, 20));

        jbtn_BuscarCP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtn_BuscarCP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/searcher2.png"))); // NOI18N
        jbtn_BuscarCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_BuscarCPMouseClicked(evt);
            }
        });
        pnl_MostrarCategoriaProducto.add(jbtn_BuscarCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 30, 30));

        btn_EliminarCP.setBackground(new java.awt.Color(126, 87, 194));
        btn_EliminarCP.setFont(new java.awt.Font("NanumMyeongjo", 1, 12)); // NOI18N
        btn_EliminarCP.setForeground(new java.awt.Color(255, 255, 255));
        btn_EliminarCP.setText("Eliminar");
        btn_EliminarCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarCPActionPerformed(evt);
            }
        });
        pnl_MostrarCategoriaProducto.add(btn_EliminarCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, 40));

        getContentPane().add(pnl_MostrarCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 470, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_MInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_MInMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_jbtn_MInMouseClicked

    private void txt_CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_CerrarMouseClicked
        dispose();
    }//GEN-LAST:event_txt_CerrarMouseClicked

    private void btn_RegistrarCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarCPActionPerformed

        String nombre = txt_NombreCP.getText();
        String descripcion = txA_DescripcionCP.getText();
        
        System.out.println(descripcion);

        try {
            cp.InsertCategoriaPD(nombre, descripcion);
        } catch (SQLException ex) {
            Logger.getLogger(VProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_RegistrarCPActionPerformed

    private void btn_ActualizarCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarCPActionPerformed
        try {
            cp.ShowDataCategoriaPD();
        } catch (SQLException ex) {
            Logger.getLogger(VProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_ActualizarCPActionPerformed

    private void jbtn_BuscarCPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_BuscarCPMouseClicked
        String buscarPor = (String)Box_BuscarCP.getSelectedItem();
        String dato = txt_BuscarCP.getText();
        String datL = "'"+dato+"'";

        System.out.println(datL);

        if(buscarPor.equals("NOMBRE") || buscarPor.equals("DESCRIPCION")){
            try {
                cp.SearchDataCategoriaPD(buscarPor, datL);
                cp.ShowDataCategoriaPD(buscarPor, datL);
            } catch (SQLException ex) {
                Logger.getLogger(VCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                cp.SearchDataCategoriaPD(buscarPor, dato);
                cp.ShowDataCategoriaPD(buscarPor, dato);
            } catch (SQLException ex) {
                Logger.getLogger(VCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtn_BuscarCPMouseClicked

    private void btn_EliminarCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarCPActionPerformed
        String id = String.valueOf((String)TablaCategoriaPD.getValueAt(TablaCategoriaPD.getSelectedRow(),0));

        try {
            cp.DeleteDataCategoriaPD(id);
        } catch (SQLException ex) {
            Logger.getLogger(VProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_EliminarCPActionPerformed

    private void jbtn_home2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_home2MouseClicked
        Home home = new Home();

        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtn_home2MouseClicked

    private void txt_NombreCPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NombreCPFocusGained
        jSeparator1.setBackground(new Color(57,113,177)); // Color del separador
        jLabel3.setForeground(new Color(57,113,177)); // Color del titulo  al seleccionar
        jLabel2.setForeground(new Color(51,52,54));
    }//GEN-LAST:event_txt_NombreCPFocusGained

    private void txA_DescripcionCPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txA_DescripcionCPFocusGained
        jLabel2.setForeground(new Color(57,113,177)); // Color del titulo al seleccionar
        jLabel3.setForeground(new Color(51,52,54));
    }//GEN-LAST:event_txA_DescripcionCPFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCategoriaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCategoriaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCategoriaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCategoriaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VCategoriaProducto().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VCategoriaProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> Box_BuscarCP;
    private javax.swing.JLabel Encabezado;
    public static javax.swing.JTable TablaCategoriaPD;
    private javax.swing.JButton btn_ActualizarCP;
    private javax.swing.JButton btn_EliminarCP;
    private javax.swing.JButton btn_RegistrarCP;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jbtn_BuscarCP;
    private javax.swing.JLabel jbtn_MIn;
    private javax.swing.JLabel jbtn_home2;
    private javax.swing.JLabel jtxt_Titulo;
    private javax.swing.JPanel pnl_Encabezado;
    private javax.swing.JPanel pnl_MostrarCategoriaProducto;
    private javax.swing.JPanel pnl_RegistroCategoriaProducto;
    private javax.swing.JTextArea txA_DescripcionCP;
    private javax.swing.JTextField txt_BuscarCP;
    private javax.swing.JLabel txt_Cerrar;
    private javax.swing.JTextField txt_NombreCP;
    // End of variables declaration//GEN-END:variables
}
