/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Logica.Login;
import MySQL_Conection.MySQL;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author breiner
 */
public class VLogin extends javax.swing.JFrame {

    Login lg = new Login();
    
    /**
     * Creates new form Home
     */
    public VLogin() {
        initComponents();
        pnl_Overlay.setBackground(new Color(0,0,0,195)); // Transparencia de la foto
        setResizable(false);
        setLocationRelativeTo(null);
        //setResizable(false);
        //setTitle("Vista Principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Overlay = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_fullName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txt_Email = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btn_SignUp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbtn_Min = new javax.swing.JLabel();
        jbtn_Cerrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_Overlay.setBackground(new java.awt.Color(0, 0, 0));
        pnl_Overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(52, 52, 54));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Welcome.png"))); // NOI18N
        pnl_Overlay.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 260, 80));

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Design, Create Awesome Swing UI");
        pnl_Overlay.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        getContentPane().add(pnl_Overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 560));

        jPanel2.setBackground(new java.awt.Color(32, 33, 35));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_fullName.setBackground(new java.awt.Color(32, 33, 35));
        txt_fullName.setForeground(new java.awt.Color(204, 204, 204));
        txt_fullName.setBorder(null);
        txt_fullName.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_fullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_fullNameFocusGained(evt);
            }
        });
        txt_fullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fullNameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_fullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 280, 20));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 280, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 280, 10));

        txt_Email.setBackground(new java.awt.Color(32, 33, 35));
        txt_Email.setForeground(new java.awt.Color(204, 204, 204));
        txt_Email.setBorder(null);
        txt_Email.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_EmailFocusGained(evt);
            }
        });
        txt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 280, 20));

        jPasswordField1.setBackground(new java.awt.Color(32, 33, 35));
        jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setBorder(null);
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 280, -1));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 280, 10));

        jLabel3.setForeground(new java.awt.Color(52, 52, 54));
        jLabel3.setText("Email");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        btn_SignUp.setBackground(new java.awt.Color(126, 87, 194));
        btn_SignUp.setFont(new java.awt.Font("NanumMyeongjo", 1, 12)); // NOI18N
        btn_SignUp.setForeground(new java.awt.Color(255, 255, 255));
        btn_SignUp.setText("Sign up");
        btn_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignUpActionPerformed(evt);
            }
        });
        jPanel2.add(btn_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 280, 40));
        btn_SignUp.getAccessibleContext().setAccessibleName("btn_signup");

        jLabel4.setForeground(new java.awt.Color(52, 52, 54));
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel5.setForeground(new java.awt.Color(52, 52, 54));
        jLabel5.setText("Fast sign up with social media");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jLabel6.setForeground(new java.awt.Color(52, 52, 54));
        jLabel6.setText("If you are already a nember please");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        jLabel7.setForeground(new java.awt.Color(57, 113, 177));
        jLabel7.setText("Signin");
        jLabel7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLabel7FocusLost(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, -1, -1));

        jLabel10.setForeground(new java.awt.Color(57, 113, 177));
        jLabel10.setText("User");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jbtn_Min.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn_Min.setForeground(new java.awt.Color(57, 113, 177));
        jbtn_Min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtn_Min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minizar2.png"))); // NOI18N
        jbtn_Min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_MinMouseClicked(evt);
            }
        });
        jPanel2.add(jbtn_Min, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 20, 30));

        jbtn_Cerrar.setForeground(new java.awt.Color(57, 113, 177));
        jbtn_Cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbtn_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close2.png"))); // NOI18N
        jbtn_Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_CerrarMouseClicked(evt);
            }
        });
        jPanel2.add(jbtn_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 20, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/facebook.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 20, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/twitter.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/google+.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        jLabel13.setForeground(new java.awt.Color(52, 52, 54));
        jLabel13.setText("Name");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(32, 33, 35));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "operador" }));
        jComboBox1.setBorder(null);
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 280, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 450, 560));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txt_fullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fullNameActionPerformed

    private void txt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailActionPerformed

    private void txt_EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_EmailFocusGained
        
        jSeparator3.setBackground(new Color(57,113,177)); // Color de las casillas al precionar
        jLabel3.setForeground(new Color(57,113,177)); // Color de los titulos al precionar
        jLabel10.setForeground(new Color(51,52,54));
        jLabel4.setForeground(new Color(51,52,54));
        jLabel13.setForeground(new Color(51,52,54));
    }//GEN-LAST:event_txt_EmailFocusGained

    private void txt_fullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fullNameFocusGained
        
        jSeparator1.setBackground(new Color(57,113,177)); // Color de las casillas al precionar
        jLabel13.setForeground(new Color(57,113,177)); // Color de los titulos al precionar
        jLabel3.setForeground(new Color(51,52,54));
        jLabel4.setForeground(new Color(51,52,54));
        jLabel10.setForeground(new Color(51,52,54));
    }//GEN-LAST:event_txt_fullNameFocusGained

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        
        jSeparator2.setBackground(new Color(57,113,177)); // Color de las casillas al precionar
        jLabel4.setForeground(new Color(57,113,177)); // Color de los titulos al precionar
        jLabel3.setForeground(new Color(51,52,54));
        jLabel10.setForeground(new Color(51,52,54));
        jLabel13.setForeground(new Color(51,52,54));
        //dispose();
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jbtn_CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_CerrarMouseClicked
        dispose(); // Cerrar
    }//GEN-LAST:event_jbtn_CerrarMouseClicked

    private void jbtn_MinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_MinMouseClicked
        this.setExtendedState(1); // Minimizar
    }//GEN-LAST:event_jbtn_MinMouseClicked

// Inicio de sesion_________________________________________________________________    
    private void btn_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignUpActionPerformed

        try {
            if(lg.Validar_Login()==1){
                
                System.out.println("Inicio de secion aprobado...");
                
                Home ho = new Home();
                ho.setVisible(true);
                this.dispose();
                
            }else{
                JOptionPane.showMessageDialog(null, "Acceso denegado","Mensaje de Acceso",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_SignUpActionPerformed
    
    
    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
        jSeparator4.setBackground(new Color(57,113,177)); // Color de las casillas al precionar
        jLabel10.setForeground(new Color(57,113,177)); // Color de los titulos al precionar
        jLabel3.setForeground(new Color(51,52,54));
        jLabel4.setForeground(new Color(51,52,54));
        jLabel13.setForeground(new Color(51,52,54));
        
    }//GEN-LAST:event_jComboBox1FocusGained

    private void jLabel7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel7FocusGained
        
    }//GEN-LAST:event_jLabel7FocusGained

    private void jLabel7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel7FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SignUp;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jbtn_Cerrar;
    private javax.swing.JLabel jbtn_Min;
    private javax.swing.JPanel pnl_Overlay;
    public static javax.swing.JTextField txt_Email;
    public static javax.swing.JTextField txt_fullName;
    // End of variables declaration//GEN-END:variables

}
